-- Logback DB schema for H2
-- Tables: logging_event, logging_event_property, logging_event_exception

CREATE TABLE IF NOT EXISTS logging_event
(
    timestmp           BIGINT      NOT NULL,
    formatted_message  CLOB        NOT NULL,
    logger_name        VARCHAR(254) NOT NULL,
    level_string       VARCHAR(254) NOT NULL,
    thread_name        VARCHAR(254),
    reference_flag     SMALLINT,
    arg0               VARCHAR(254),
    arg1               VARCHAR(254),
    arg2               VARCHAR(254),
    arg3               VARCHAR(254),
    caller_filename    VARCHAR(254),
    caller_class       VARCHAR(254),
    caller_method      VARCHAR(254),
    caller_line        CHAR(4),
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS logging_event_property
(
    event_id          BIGINT       NOT NULL,
    mapped_key        VARCHAR(254) NOT NULL,
    mapped_value      CLOB,
    PRIMARY KEY (event_id, mapped_key),
    FOREIGN KEY (event_id) REFERENCES logging_event(event_id)
);

CREATE TABLE IF NOT EXISTS logging_event_exception
(
    event_id         BIGINT  NOT NULL,
    i                SMALLINT NOT NULL,
    trace_line       CLOB    NOT NULL,
    PRIMARY KEY (event_id, i),
    FOREIGN KEY (event_id) REFERENCES logging_event(event_id)
);
